name: Deploy Frontend
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t majdie40/docker-react -f Dockerfile.dev